### ISSUE TITLE
Missing manual leveling macro in Dual and Quad.

### ISSUE THREAD

**Issue by daniel-farina** [PrintM3D/Crane#57] opened 2018-12-11 14:51 UTC
While revising the instructions for the Crane Quad I found the following issue here: 

https://crane.printm3d.com/crane-quad-guide/manual-bed-leveling-assistant

This Quad Instructions claim there should be a calibration section called Calibration > manual bed leveling. 
![image](https://user-images.githubusercontent.com/13665117/49808191-f1fa4f80-fd29-11e8-9ab6-772bf95da208.png)
but this is what I found instead: 
![image](https://user-images.githubusercontent.com/13665117/49808228-09d1d380-fd2a-11e8-9017-6e90ed72f852.png)

The first thing I did is to go to the Github repo to locate the correct Macros here: https://github.com/PrintM3D/Crane/tree/dev/SD%20Card%20Structure/Quad/macros
but it seems outdated.

Possible solution but I'm not sure if the macro would be the same, I'm pretty  sure they are not:
It seems the Calibration macros and folder is only available in the Bowden folder in Github here: 
https://github.com/PrintM3D/Crane/tree/dev/SD%20Card%20Structure/Bowden/macros/Calibration
and missing in both the Dual and Quad folder. 

Please confirm.

**Comment by daniel-farina** [comment] 2018-12-11 14:56
I suggest also giving options in the instructions: 

For example: Use the macro located at or run the following g code
```
G32;
```
We can do this using the tabs in Gitbooks. @shoreliner

**Comment by slipstreamliner** [comment] 2018-12-12 17:32
Issue has been confirmed and is currently in the process of being patched.  See a5188a6 for details.  The branch /rc5patch/ has been created to handle this update. The current issues that have been caused by transitioning from RC2 ->RC5 are being handled separately in the rc5branch.  Following completion, it will be merged back to dev.

**Comment by slipstreamliner** [comment] 2018-12-18 21:45
New Leveling Macro has been added per the merge with /rc5patch/ branch.

**Closed as completed by slipstreamliner** 2018-12-18 21:45 UTC
Labels: bug, Crane Line
