### ISSUE TITLE
(Enhancement) Stop Print

### ISSUE THREAD

**Issue by Tylerun** [PrintM3D/Crane#65] opened 2018-12-28 21:40 UTC
Please add a stop print command into the tuning menu.

**Comment by slipstreamliner** [comment] 2018-12-31 18:29
This feature was intended for inclusion and will be resolved with an inline commit. Thanks.

**Comment by slipstreamliner** [comment] 2019-01-14 20:42
For now, I've added the Cancel Print command(M0, unconditional stop).  Do we have a reason to include stop instead of cancel?

This will be milestoned now and released in the 2.02 official patch.

**Comment by Tylerun** [comment] 2019-01-15 02:03
Nope same thing close away

**Comment by slipstreamliner** [comment] 2019-01-18 15:20
@Tylerun If you're available to test today, just grab /202patch branch and ensure your maestro is on 2.02 Firmware(Official Release from dc42).

I'll be fine tuning this and other options relative to how the menu system and the system configuration handle pause/stop/cancel commands.

**Comment by ericl-m3d** [comment] 2019-04-22 21:34
CANCEL option has been added. Refer to commits below:
2ba523a
9405f87
b7ceadd

NOTE: For now, we will consider STOP and CANCEL the same command.

**Closed as completed by ericl-m3d** 2019-04-22 21:34 UTC
Labels: enhancement, Crane Line
