### ISSUE TITLE
(Bug) Display has a value of "100" in top left corner.

### ISSUE THREAD

**Issue by bass4aj** [PrintM3D/Crane#67] opened 2019-01-02 03:07 UTC
Top left corner of the display has a floating value of 100 over the "Nozzle" text.

**Comment by Tylerun** [comment] 2019-01-03 20:44
Which firmware and which printer are you using to get this?

**Comment by bass4aj** [comment] 2019-01-03 20:49
Crane Quad, Firmware 2.02 DWC 1.22.6, though I had this issue prior to
upgrading my firmware. I think I was on RC3.

**Comment by Tylerun** [comment] 2019-01-03 20:55
I had the same issue upon updating to prerelease version of firmware try updating to release

**Comment by bass4aj** [comment] 2019-01-03 20:59
As in the Crane release? My firmware is on 2.02 release right now.

**Comment by Tylerun** [comment] 2019-01-03 21:03
So if you look at your printer does it say crane quad in the lower left corner

**Comment by bass4aj** [comment] 2019-01-03 21:04
I think it just says "Quad", but I will have to check when I get home.

**Comment by Tylerun** [comment] 2019-01-03 21:10
https://youtu.be/hO7-jUEo5Q4
https://youtu.be/QBarLjX7M_M

Try following one of these depending what you use. Duet interface or sd card see if it fixes it

**Comment by Tylerun** [comment] 2019-01-05 21:42
Did you get any results?

**Comment by bass4aj** [comment] 2019-01-07 15:53
Ah yeah it says crand quad

**Comment by bass4aj** [comment] 2019-01-07 15:54
Didn't have a chance to try the videos you sent. On vacation now til next
week

**Comment by slipstreamliner** [comment] 2019-01-14 20:40
This is typically caused by ghosting of the menu system. In other words, populating similar rows and columns as a value that already exists.  This should have been resolved in the latest official release.

**Comment by slipstreamliner** [comment] 2019-01-14 20:49
@bass4aj in this case you need to download the official release, which includes the /menu folder.  Because these issues were resolved with a change in the menu configuration, rather than the firmware itself, it will require you to update the entire /menu folder on your duet's sd card.

Please reopen if you have any more issues with this -- after reading over I am fairly positive this will solve your issue, however.

**Closed as completed by slipstreamliner** 2019-01-14 20:49 UTC
